apiVersion: v1
kind: Service
metadata:
  name: nomad-server
  labels:
    app: nomad
    component: server
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
  selector:
    app: nomad
    component: server
---
apiVersion: v1
kind: Service
metadata:
  name: nomad-server-lb
  labels:
    app: nomad
    component: server
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: nomad
    component: server
